# Generated by Django 3.2.6 on 2021-10-31 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxo_caixa', '0002_auto_20211031_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancameto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_documento', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_caixa.categoria')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='Plano_Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.AddField(
            model_name='lancameto',
            name='plano_conta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo_caixa.plano_conta'),
        ),
        migrations.AddField(
            model_name='lancameto',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
