# Generated by Django 3.2.6 on 2021-10-31 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxo_caixa', '0003_auto_20211031_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lancameto',
            new_name='Lancamento',
        ),
    ]
