# Generated by Django 3.2.6 on 2021-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0005_plano_conta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano_conta',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
