# Generated by Django 3.2.6 on 2021-11-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0006_alter_plano_conta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='user_id',
            new_name='user',
        ),
    ]
