# Generated by Django 3.2.6 on 2021-11-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0007_rename_user_id_lancamento_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='plano_conta_id',
            new_name='plano_conta',
        ),
    ]
