# Generated by Django 3.2.6 on 2021-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0008_rename_plano_conta_id_lancamento_plano_conta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano_conta',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], default='R', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
