# Generated by Django 3.2.6 on 2021-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0010_alter_plano_conta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipo',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa'), ('S', 'Saida'), ('E', 'Entrada')], max_length=1),
        ),
    ]
