# Generated by Django 3.2.6 on 2021-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo_caixa', '0011_alter_lancamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(),
        ),
    ]
