# Generated by Django 3.2.6 on 2021-10-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
